### ISSUE TITLE
gltools/gltools.pxd:5:0: 'geotools.pxd' not found

### ISSUE THREAD

**Issue by elmarquez** [tenko/gltools#1]
Runar;

This is perhaps less of an issue posting than a request for assistance.  I've been attempting to compile gltools so that I can try out your occmodel library but have not had any luck. I'm compiling on Ubuntu Linux 3.2.0-35, with Python 2.7.3.

This is a pastebin of the command execution and output error:

http://pastebin.com/EZac7Y42

Here is an abbreviated listing of the error:

gltools/gltools.pxd:5:0: 'geotools.pxd' not found

...

gltools/gltools.pxd:5:0: 'Point.pxd' not found

Error compiling Cython file:

...

gltools/gltools.pxd:162:18: 'Transform' is not a type identifier

building 'gltools' extension
gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -Igltools/@include -Igltools/@src -Igltools/@contrib -I/usr/include/python2.7 -c gltools/gltools.cpp -o build/temp.linux-x86_64-2.7/gltools/gltools.o -fpermissive
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for Ada/C/ObjC but not for C++ [enabled by default]
gltools/gltools.cpp:1:2: error: #error Do not use this file, it is the result of a failed Cython compilation.
Traceback
:error: command 'gcc' failed with exit status 1

I appreciate any advice you may provide. Thanks in advance,

Davis

**Comment by tenko** [comment]
You are missing the 'geotools' build time dependency. E.g. the 'geotools.pxd' include file for Cython
compilation is missing. This is not installed by the 'geotools' Distutils script as I could not find a way
of adding it to the 'site-package' folder. 

Try to copy the missing file manually where Cython can find it.
